[global]
excludes = [
  "flake.lock",
  "**/.gitignore",
  "**/.gitmodules",
  ".gitignore",
  ".gitmodules",
  "LICENSE",
  "systems/discovery/firmware/*",
  "secrets",
  "assets/wallpapers",
  "*.png",
  "*.webp",
  "*.jpg",
  "*.md",
  "*.mp3",
  "*.icon",
  "home-manager/programs/files/*",
  "*.diff",
  "*.svg",
  "**/lazy-lock.json",
  "*.conf",
  "*.rasi",
  "*.css",
  "*.json",
  "home-manager/programs/nwg-dock-hyprland/nwg-dock-pinned",
  "home-manager/programs/direnv/direnvrc",
]


[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.lua]
command = "stylua"
includes = ["*.lua"]

[formatter.toml]
command = "taplo"
options = ["format", "$@"]
includes = ["*.toml"]

[formatter.beautysh]
command = "beautysh"
includes = ["*.sh", "*.zsh", "assets/scripts/*"]
