#!/usr/bin/env bash

stream() {
    echo "starting stream"
    streamlink -p mpv --title="[TTV-ROFI] {author} - {game} - {title}" "https://twitch.tv/$1" best &
}

chat() {
    echo "starting chat"
    # firefox --kiosk -P "twitch" "https://twitch.tv/$1/chat" & # NOTE: quite laggy + kiosk resize adds top bar again
    chatterino -c "$1;/mentions" &
}

points() {
    echo "start collecting points"
    docker start twitch-miner
}

streamer=$(/home/armin/.config/zsh/streamer_list)

streamer_select=$( echo "$streamer" | rofi -dmenu)

stream "$streamer_select"
chat "$streamer_select"
points "$streamer_select"
echo "sleep for 10s"
sleep 10 # wait for everything to laod
hypr-save -a=twitch # load window config
